export type TargetLanguage = 'luau' | 'typescript';

export interface GenerationRequest {
  language: TargetLanguage;
  name: string;
  description?: string;
  prompt: string;
}

export interface GenerationResult {
  language: TargetLanguage;
  code: string;
  generatedAt: string;
  metadata: {
    name: string;
    description?: string;
  };
}

export class CodeGenerator {
  generate(request: GenerationRequest): GenerationResult {
    const code = request.language === 'luau'
      ? `-- ${request.name}\n-- Generated by LUMI\n\n${request.prompt}\n`
      : `// ${request.name}\n// Generated by LUMI\n\n${request.prompt}\n`;

    return {
      language: request.language,
      code,
      generatedAt: new Date().toISOString(),
      metadata: {
        name: request.name,
        description: request.description,
      },
    };
  }

  supportedLanguages(): TargetLanguage[] {
    return ['luau', 'typescript'];
  }
}
