function compileVisualScript(graph) {
  const lines = ['-- Auto-generated by Visual Scripting Engine', ''];
  const nodes = graph && Array.isArray(graph.nodes) ? graph.nodes : [];

  nodes.forEach((node) => {
    if (node && node.type === 'Event') {
      lines.push(`local function on_${node.event || 'event'}(player)`);
    }

    if (node && node.type === 'Action') {
      if (node.action === 'GiveCurrency') {
        const amount = node.inputs && node.inputs.amount != null ? node.inputs.amount : 0;
        lines.push(`player:SetAttribute("Coins", (player:GetAttribute("Coins") or 0) + ${amount})`);
      }

      if (node.action === 'PlaySound') {
        const soundId = node.inputs && node.inputs.soundId ? node.inputs.soundId : 'rbxassetid://0';
        lines.push('local sound = Instance.new("Sound")');
        lines.push(`sound.SoundId = "${soundId}"`);
        lines.push('sound:Play()');
      }
    }

    if (node && node.type === 'Event') {
      lines.push('end');
      lines.push('');
    }
  });

  return lines.join('\n').trimEnd();
}

module.exports = { compileVisualScript };
