import { TimelineClip } from '../orchestration/ProductionContracts';

export interface EditorOptions {
  aiEditing: boolean;
  automaticTiming: boolean;
  captions: boolean;
  motionGraphics: boolean;
}

export class TimelineEditor {
  edit(clips: TimelineClip[], options: EditorOptions): TimelineClip[] {
    const edited = [...clips];

    if (options.aiEditing) {
      edited.sort((left, right) => left.startSeconds - right.startSeconds);
    }

    if (options.automaticTiming) {
      let cursor = 0;
      edited.forEach((clip) => {
        clip.startSeconds = cursor;
        cursor += clip.durationSeconds;
      });
    }

    if (options.captions) {
      edited.push({
        id: `title-${Date.now()}`,
        type: 'title',
        startSeconds: 0,
        durationSeconds: 4,
        payload: { text: 'Generated by LUMI' },
      });
    }

    if (options.motionGraphics) {
      edited.push({
        id: `fx-${Date.now()}`,
        type: 'effect',
        startSeconds: Math.max(0, edited.length - 1),
        durationSeconds: 3,
        payload: { effect: 'parallax' },
      });
    }

    return edited;
  }
}
